### ISSUE TITLE
Bug - signal_display/create_conglomerate_disconts function, Adding aditional channels to Channels window

### ISSUE THREAD

**Issue by SweetVlad** [ICRC-BME/PySigView#1]
1. add channel_1 to channel window
2. add channel_2 to separately (after the first one is visualized) - error in signal_display/create_conglomerate_disconts function

> Traceback (most recent call last):
>   File "PySigView/pysigview/widgets/signal_display.py", line 822, in update_data_map_channels
>     self.create_conglomerate_disconts()
>   File "PySigView/pysigview/widgets/signal_display.py", line 740, in create_conglomerate_disconts
>     & (disconts[i] < proc_stop)]
> ValueError: operands could not be broadcast together with shapes (10,) (10,2)

**Comment by cimbi** [comment]
I cannot reproduce this. What version of pysigview / python. Works fine on my Ubuntu machine

**Comment by SweetVlad** [comment]
last version of pysigview, python 3.6, macOS High Sierra

I get this warning when the app is starting : "anaconda3/lib/python3.6/site-packages/vispy/visuals/isocurve.py:22: UserWarning: VisPy is not yet compatible with matplotlib 2.2+
  warnings.warn("VisPy is not yet compatible with matplotlib 2.2+")"

Adding channels with no discontinuities works fine. The Error might be related to processing discontinuities in different channels. Maybe with just different disconts in each channel?

**Comment by cimbi** [comment]
Ah, yes. I see that now. OK, will check that.
