### ISSUE TITLE
autoscale - not working properly

### ISSUE THREAD

**Issue by SweetVlad** [ICRC-BME/PySigView#14]
When autoscale is active - newly added channels won't be autoscaled

design change:
- Each channel scaling should be independent
- Each channel setting should be adjustable individually after the global setting is applied.

**Comment by cimbi** [comment]
this will be solved with the "Master channel" feature. the newly added channels will inherit the settings from the master channel. if no master channel is set, the newly added channels will inherit the settings which are similar to the majority of the channels
