### ISSUE TITLE
open second file error

### ISSUE THREAD

**Issue by pklimes** [ICRC-BME/PySigView#19]
**Describe the bug**
Opening new file, while still viewing the previous one, makes viewer exit.

**To Reproduce**
1. File > open file
2. after loading, move signals from panel to viewing area
3. File > open file (different file)
4. See error (viewer closes down)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.1 LTS
 - PySigView Version [e.g. 22]

**Comment by cimbi** [comment]
Fixed by commit 008ce37f7701cd2b387c639f3d8e1bfd3fc7e2da. Will be released in version v.0.0.0-alpha.5
