### ISSUE TITLE
Establish connection to database when "enter" is pressed when editing password window

### ISSUE THREAD

**Issue by vodyn** [ICRC-BME/PySigView#27]
**Describe the bug**

**To Reproduce**

**Expected behavior**
When filling up the password to database, it would be beneficial just to hit enter to establish connection instead of clicking on "Connect" button

**Screenshots**

**Desktop (please complete the following information):**
 - PySigView Version [e.g. 22]

**Additional context**

**Comment by cimbi** [comment]
please provide more concise description. I don't understand the problem
