### ISSUE TITLE
Suggestion - amplitude and units bar for each channel / different way to visualize amplitudes and units

### ISSUE THREAD

**Issue by SweetVlad** [ICRC-BME/PySigView#4]
- units marker - for visual evaluation of signals, an essential tool

- Implementation - display amplitude and units on the left side, utilize grid for visualization? Each channel with grid on is now discrete with 10 intervals.

- additional remarks - autoscale stretches each signal differentially, but there is no way to correct or change it --> implement channel independent manual channel scaling.

**Comment by cimbi** [comment]
This was introduced by commit 5e3a292e95b14a162768a9260d09daffc9a6b581 in version v0.0.0-alpha.5
