### ISSUE TITLE
bug - Annotations graphics is visible after annotation set was deleted from UI

### ISSUE THREAD

**Issue by SweetVlad** [ICRC-BME/PySigView#5]
Annotations graphics stay in display and it is never redrawn.

<img width="1074" alt="screenshot 2018-10-02 13 17 58" src="https://user-images.githubusercontent.com/23422467/46368366-a6e70080-c645-11e8-9e75-9a74d2db255b.png">

MacOS High Sierra, python v3.6, Pysigview Master

**Comment by cimbi** [comment]
how do you replicate this?

**Comment by SweetVlad** [comment]
1. create or open the annotation set
2. make annotation which is visible in the display
3. select "delete item" upon right-click on the annotation
4. graphics from this annotation stay in the display even with moving to different time
