### ISSUE TITLE
ability to remove annotations

### ISSUE THREAD

**Issue by SweetVlad** [ICRC-BME/PySigView#7]
- make annotations removable in the display.

- visualize annotation positions in the navigation bar (as a mark)?

- (future) categorical colors - different colors for specific annotations - why -> sleep visualizations/scoring (Now it is possible to do it with multiple annotations sets of different colors)

**Comment by cimbi** [comment]
Ad 1) This is already implemented - by clinking on the tick button next to the annotation group in annotation widget

Ad 2) Will be implemented in the future, however this is difficult when there is a lot of annotations - the bar becomes full of them

Ad 3) This is already possible by rightclicking on the annotation set which will bring a dialog for subset creations. Then each subset can be treated as a standard annotation set.

**Comment by SweetVlad** [comment]
re 1) I don't know how it is done. I can delete the whole annotation set(all annotation inside are gone), or I can create subset items - each annotation separated but it if you remove one subset item it remains in main annotation set, and it is not deleted

re 3) I see - it is made for df with category column.

**Comment by cimbi** [comment]
ad 1) the subsets are just "views" of the main annotation set. If you just don't want to see them, then remove the tick to the left of the subset. Otherwise it is not possible (and likely not desirable) to delete them.

**Comment by SweetVlad** [comment]
re 1) ok I understand now, but I think it is desirable to be able to change position or delete individual annotation when you are annotating some signal. If a mistake is made (wrong channel/position/interval), the annotation stays in the annotation set, and you cannot remove it.

**Comment by cimbi** [comment]
Ah, yes. That's right.
